version: '3'

services:

  config-server:
    container_name: config-server
    build: ./config-server
    ports:
      - "8888:8888"
      - "18787:8787"

  service-registry:
    container_name: service-registry
    build: ./service-registry
    ports:
      - "8761:8761"
      - "28787:8787"
    depends_on:
      - config-server

  zipkin-server:
    image: openzipkin/zipkin
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/tree/1.19.0/zipkin-server#environment-variables
    environment:
      - STORAGE_TYPE=mem
      # Uncomment to disable scribe
      # - SCRIBE_ENABLED=false
      # Uncomment to enable self-tracing
      - SELF_TRACING_ENABLED=false
      # Uncomment to enable debug logging
      # - JAVA_OPTS=-Dlogging.level.zipkin=DEBUG
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411

  catalog-service:
      container_name: catalog-service
      build: ./catalog-service
      ports:
        - "18181:8181"
        - "19797:8787"
      depends_on:
        - config-server
        - service-registry
      entrypoint: /bin/sh
      command: >
        -c "
        while ! (nc -z config-server 8888 && nc -z service-registry 8761); do sleep 5; echo 'Waiting for service-registry and config-server services to start-up...'; done;
        java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8787,suspend=n -jar -Dspring.profiles.active=docker /app.jar
        "

  inventory-service:
      container_name: inventory-service
      build: ./inventory-service
      ports:
        - "18282:8282"
        - "29797:8787"
      depends_on:
        - config-server
        - service-registry
      entrypoint: /bin/sh
      command: >
        -c "
        while ! (nc -z config-server 8888 && nc -z service-registry 8761); do sleep 5; echo 'Waiting for service-registry and config-server services to start-up...'; done;
        java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8787,suspend=n -jar -Dspring.profiles.active=docker /app.jar
        "

  product-service:
      container_name: product-service
      build: ./product-service
      ports:
        - "18383:8383"
        - "39797:8787"
      depends_on:
        - config-server
        - service-registry
      entrypoint: /bin/sh
      command: >
        -c "
        while ! (nc -z config-server 8888 && nc -z service-registry 8761); do sleep 5; echo 'Waiting for vault and config-server services to start-up...'; done;
        java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8787,suspend=n -jar -Dspring.profiles.active=docker /app.jar
        "
